version: '3'
services:
    orb:
        build:
            context: ./dockerfile
            dockerfile: Dockerfile
        restart: on-failure
        container_name: orb
        volumes:
            - './data/orb_daufalt.yaml:/orb_daufalt.yaml'
        shm_size: '1gb'
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: "nvidia"
                          count: "all"
                          capabilities: ["gpu"]
        stdin_open: true
        tty: true
